"""Authentication constants."""

# Token defaults
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 15
DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS = 7
DEFAULT_JWT_ALGORITHM = "HS256"

# Password
DEFAULT_BCRYPT_ROUNDS = 12

# TOTP
DEFAULT_TOTP_ISSUER = "Dhanada"
DEFAULT_TOTP_WINDOW = 1
DEFAULT_TOTP_DIGITS = 6
DEFAULT_TOTP_PERIOD = 30
BACKUP_CODE_COUNT = 5
BACKUP_CODE_LENGTH = 16

# Session
DEFAULT_SESSION_TOKEN_BYTES = 32

# Encryption
KEK_SIZE = 32  # 256 bits
DEK_SIZE = 32  # 256 bits
AES_GCM_NONCE_SIZE = 12  # 96 bits
AES_GCM_TAG_SIZE = 16  # 128 bits

# Database
UUID_LENGTH = 36
EMAIL_MAX_LENGTH = 255
USERNAME_MAX_LENGTH = 100
PASSWORD_HASH_MAX_LENGTH = 255
FULL_NAME_MAX_LENGTH = 200
ROLE_NAME_MAX_LENGTH = 50
RESOURCE_MAX_LENGTH = 100
ACTION_MAX_LENGTH = 50
USER_AGENT_MAX_LENGTH = 500
IP_ADDRESS_MAX_LENGTH = 45

# Rate limiting (for future use)
DEFAULT_RATE_LIMIT_REQUESTS = 100
DEFAULT_RATE_LIMIT_WINDOW = 60

# App membership — maps resources to app slugs
RESOURCE_APP_MAP: dict[str, str] = {
    "clients": "crm",
    "documents": "crm",
}
